import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateInitialSchema20260921200000 implements MigrationInterface {
  name = 'CreateInitialSchema20260921200000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    await queryRunner.query("CREATE TYPE \"user_role\" AS ENUM ('PROFESSOR', 'ADMIN')")
    await queryRunner.query("CREATE TYPE \"lab_status\" AS ENUM ('liberado', 'bloqueado')")
    await queryRunner.query("CREATE TYPE \"history_action\" AS ENUM ('BLOCK_INTERNET', 'UNBLOCK_INTERNET')")

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "username" varchar(64) NOT NULL,
        "email" varchar(255) NOT NULL,
        "password_hash" varchar(255) NOT NULL,
        "role" "user_role" NOT NULL DEFAULT 'PROFESSOR',
        "is_active" boolean NOT NULL DEFAULT false,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_users_username" UNIQUE ("username"),
        CONSTRAINT "UQ_users_email" UNIQUE ("email")
      )
    `)
    await queryRunner.query(`
      CREATE TABLE "labs" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        "name" varchar(120) NOT NULL,
        "block" varchar(80) NOT NULL,
        "subnet" cidr NOT NULL,
        "status" "lab_status" NOT NULL DEFAULT 'bloqueado',
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "UQ_labs_name" UNIQUE ("name"),
        CONSTRAINT "UQ_labs_subnet" UNIQUE ("subnet")
      )
    `)
    await queryRunner.query(`
      CREATE TABLE "histories" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        "user_id" uuid NOT NULL,
        "username_snapshot" varchar(64) NOT NULL,
        "lab_id" integer NOT NULL,
        "lab_name_snapshot" varchar(120) NOT NULL,
        "action" "history_action" NOT NULL,
        "previous_status" "lab_status" NOT NULL,
        "new_status" "lab_status" NOT NULL,
        "request_id" uuid,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "FK_histories_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT,
        CONSTRAINT "FK_histories_lab" FOREIGN KEY ("lab_id") REFERENCES "labs" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT
      )
    `)
    await queryRunner.query(`
      CREATE TABLE "refresh_sessions" (
        "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        "user_id" uuid NOT NULL,
        "token_hash" varchar(255) NOT NULL,
        "expires_at" timestamptz NOT NULL,
        "revoked_at" timestamptz,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "FK_refresh_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE RESTRICT
      )
    `)

    await queryRunner.query('CREATE INDEX "IDX_histories_user_created_at" ON "histories" ("user_id", "created_at")')
    await queryRunner.query('CREATE INDEX "IDX_histories_lab_created_at" ON "histories" ("lab_id", "created_at")')
    await queryRunner.query('CREATE INDEX "IDX_histories_request_id" ON "histories" ("request_id") WHERE "request_id" IS NOT NULL')
    await queryRunner.query('CREATE INDEX "IDX_refresh_sessions_user_id" ON "refresh_sessions" ("user_id")')
    await queryRunner.query('CREATE INDEX "IDX_refresh_sessions_expires_at" ON "refresh_sessions" ("expires_at")')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "refresh_sessions"')
    await queryRunner.query('DROP TABLE "histories"')
    await queryRunner.query('DROP TABLE "labs"')
    await queryRunner.query('DROP TABLE "users"')
    await queryRunner.query('DROP TYPE "history_action"')
    await queryRunner.query('DROP TYPE "lab_status"')
    await queryRunner.query('DROP TYPE "user_role"')
  }
}
