version: '3'

services:
  db:
    container_name: 'db'
    image: postgres:14
    environment:
      POSTGRES_DB: api-firewall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
